services:
  - type: web
    name: fossee-chemical-frontend-v2
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://fossee-chemicalapp-production.up.railway.app/api
    rewriteRules:
      - source: (.*)
        destination: /index.html
